server:
  port: 3930


spring:
  application:
    name: Sentiment

  datasource:
    url: jdbc:mysql://localhost:3306/sentiment?useSSL=false&serverTimezone=UTC
    username: root
    password: susheel@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  redis:
    host: localhost
    port: 6379
    timeout: 2000




